apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-pipeline-demo
  template:
    metadata:
      labels:
        app: cicd-pipeline-demo
    spec:
      containers:
        - name: cicd-pipeline-demo
          image: idriss98/cicd-pipeline-demo:latest  # Your Docker Hub image
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:  # Only needed for private images
        - name: dockerhub-creds
