apiVersion: v1
kind: Service
metadata:
  name: cicd-pipeline-demo-service
spec:
  selector:
    app: cicd-pipeline-demo  # Matches deployment labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Matches containerPort
  type: NodePort  # For Minikube access (or LoadBalancer in cloud)
